export const GET_EVENTS_LOADING = "GET_EVENTS_LOADING";

export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";

export const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";

export const UPDATE_EVENTS_COUNT = "UPDATE_EVENTS_COUNT";
